global:
  scrape_interval: 1s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus default metrics

  - job_name: 'celery_scraper'
    static_configs:
      - targets: ['localhost:8000']  # Celery task metrics
